BEGIN;

CREATE TABLE test_strings (string TEXT);
INSERT INTO test_strings VALUES ($$$$);
INSERT INTO test_strings VALUES ($$  $$);
INSERT INTO test_strings VALUES ($$"$$);
INSERT INTO test_strings VALUES ($$[,]$$);
INSERT INTO test_strings VALUES ($$[)$$);
INSERT INTO test_strings VALUES ($$[]]$$);
INSERT INTO test_strings VALUES ($$[}$$);
INSERT INTO test_strings VALUES ($${,}$$);
INSERT INTO test_strings VALUES ($${]$$);
INSERT INTO test_strings VALUES ($$["1":2]$$);
INSERT INTO test_strings VALUES ($$[1,2,]$$);
INSERT INTO test_strings VALUES ($$[1:2}$$);
INSERT INTO test_strings VALUES ($${"1":2,}$$);
INSERT INTO test_strings VALUES ($${1:2}$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"], [7 ]}]}$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"], [7]}]}$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"], "7" :[8 ]}]$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"], "7" :[8 ]}]]$$);
INSERT INTO test_strings VALUES ($${"1":2, "3":4$$);
INSERT INTO test_strings VALUES ($$"1\u2"$$);
INSERT INTO test_strings VALUES ($$[,2]$$);
INSERT INTO test_strings VALUES ($$"3$$);
INSERT INTO test_strings VALUES ($$"3" "4"$$);
INSERT INTO test_strings VALUES ($$[3[4]$$);
INSERT INTO test_strings VALUES ($$[3[4]]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6] 7, 8 9]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6] 7, 8, 9]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6], 7, 8 9]$$);
INSERT INTO test_strings VALUES ($${"hello":true, "bye":false, null}$$);
INSERT INTO test_strings VALUES ($${"hello":true, "bye":false, null:null}$$);
INSERT INTO test_strings VALUES ($$"hi$$);
INSERT INTO test_strings VALUES ($$"hi"""$$);
INSERT INTO test_strings VALUES ($${"hi": "bye"]$$);
INSERT INTO test_strings VALUES ($$"\uD800\uD800"$$);
INSERT INTO test_strings VALUES ($$"\uD800\uDBFF"$$);
INSERT INTO test_strings VALUES ($$"\UD834\UDD1E"$$);
INSERT INTO test_strings VALUES ($$"\uDB00"$$);
INSERT INTO test_strings VALUES ($$"\uDB00\uDBFF"$$);
INSERT INTO test_strings VALUES ($$"\uFFFE"$$);
INSERT INTO test_strings VALUES ($$"\uFFFF"$$);
INSERT INTO test_strings VALUES ($$.$$);
INSERT INTO test_strings VALUES ($$""$$);
INSERT INTO test_strings VALUES ($$[]$$);
INSERT INTO test_strings VALUES ($${}$$);
INSERT INTO test_strings VALUES ($$+.$$);
INSERT INTO test_strings VALUES ($$0.5$$);
INSERT INTO test_strings VALUES ($$0.e1$$);
INSERT INTO test_strings VALUES ($${"1":{}}$$);
INSERT INTO test_strings VALUES ($${"1":2}$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"]}]}$$);
INSERT INTO test_strings VALUES ($${"1":2, "2.5" : [3, 4, {}, {"5": ["6"], "7" :[8 ]}]}$$);
INSERT INTO test_strings VALUES ($$1234$$);
INSERT INTO test_strings VALUES ($$-1234$$);
INSERT INTO test_strings VALUES ($${"1":2, "3":4}$$);
INSERT INTO test_strings VALUES ($$+1234$$);
INSERT INTO test_strings VALUES ($$++1234$$);
INSERT INTO test_strings VALUES ($$123.456e14234$$);
INSERT INTO test_strings VALUES ($$123.456e-14234$$);
INSERT INTO test_strings VALUES ($$123.456e+14234$$);
INSERT INTO test_strings VALUES ($$123.e-14234$$);
INSERT INTO test_strings VALUES ($$"1\u2000"$$);
INSERT INTO test_strings VALUES ($$"1\u20001"$$);
INSERT INTO test_strings VALUES ($$2$$);
INSERT INTO test_strings VALUES ($$.246e-14234$$);
INSERT INTO test_strings VALUES ($$.2e-14234$$);
INSERT INTO test_strings VALUES ($$3$$);
INSERT INTO test_strings VALUES ($$.3$$);
INSERT INTO test_strings VALUES ($$"3"$$);
INSERT INTO test_strings VALUES ($$[3]$$);
INSERT INTO test_strings VALUES ($$+3.$$);
INSERT INTO test_strings VALUES ($$3.2e+1$$);
INSERT INTO test_strings VALUES ($$[3, [4]]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5]]]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6]]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6], 7]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6], 7, 8]$$);
INSERT INTO test_strings VALUES ($$[3, [4, [5], 6], 7, 8, 9]$$);
INSERT INTO test_strings VALUES ($$+3.5$$);
INSERT INTO test_strings VALUES ($$.3e$$);
INSERT INTO test_strings VALUES ($$.3e1$$);
INSERT INTO test_strings VALUES ($$.3e-1$$);
INSERT INTO test_strings VALUES ($$.3e+1$$);
INSERT INTO test_strings VALUES ($$3.e1$$);
INSERT INTO test_strings VALUES ($$3.e+1$$);
INSERT INTO test_strings VALUES ($$3e+1$$);
INSERT INTO test_strings VALUES ($$.5$$);
INSERT INTO test_strings VALUES ($$+.5$$);
INSERT INTO test_strings VALUES ($$.5e+1$$);
INSERT INTO test_strings VALUES ($$[ 7]$$);
INSERT INTO test_strings VALUES ($$[7 ]$$);
INSERT INTO test_strings VALUES ($$[7]$$);
INSERT INTO test_strings VALUES ($$.e-14234$$);
INSERT INTO test_strings VALUES ($$"hello"$$);
INSERT INTO test_strings VALUES ($$["hello"]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye"]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n"]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t"]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t\b"]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t\b",true]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t\b",true , false]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t\b",true , false,    null]$$);
INSERT INTO test_strings VALUES ($$["hello", "bye\n\r\t\v"]$$);
INSERT INTO test_strings VALUES ($${"hello":true}$$);
INSERT INTO test_strings VALUES ($${"hello":true, "bye":false}$$);
INSERT INTO test_strings VALUES ($${"hello":true, "bye":false, "foo":["one","two","three"]}$$);
INSERT INTO test_strings VALUES ($$"hi"$$);
INSERT INTO test_strings VALUES ($$["hi"]$$);
INSERT INTO test_strings VALUES ($$["hi", "bye"]$$);
INSERT INTO test_strings VALUES ($${"hi": "bye"}$$);
INSERT INTO test_strings VALUES ($$["hi", "bye", 3]$$);
INSERT INTO test_strings VALUES ($$["hi", "bye[", 3]$$);
INSERT INTO test_strings VALUES ($$"\u0007"$$);
INSERT INTO test_strings VALUES ($$"\u0008"$$);
INSERT INTO test_strings VALUES ($$"\u0009"$$);
INSERT INTO test_strings VALUES ($$"\u0010"$$);
INSERT INTO test_strings VALUES ($$"\u0020"$$);
INSERT INTO test_strings VALUES ($$"\u10000"$$);
INSERT INTO test_strings VALUES ($$"\u1234"$$);
INSERT INTO test_strings VALUES ($$"\u99999"$$);
INSERT INTO test_strings VALUES ($$"\ud800\udc00"$$);
INSERT INTO test_strings VALUES ($$"\uD800\uDC00"$$);
INSERT INTO test_strings VALUES ($$"\uD834\uDD1E"$$);
INSERT INTO test_strings VALUES ($$"\uDBFF\uDFFF"$$);
INSERT INTO test_strings VALUES ($$"\uFFFD"$$);
INSERT INTO test_strings VALUES ($$"\uFFFF"$$);
INSERT INTO test_strings VALUES ($$hello$$);
INSERT INTO test_strings VALUES ($$[32, 1]$$);
INSERT INTO test_strings VALUES ($$[32, $$);
INSERT INTO test_strings VALUES ($$"\uD800\uDC00"$$);
INSERT INTO test_strings VALUES ($$"\n"$$);
INSERT INTO test_strings VALUES ($$"hello"$$);
INSERT INTO test_strings VALUES ($$"hello\u0009world"$$);
INSERT INTO test_strings VALUES ($$"hello"$$);
INSERT INTO test_strings VALUES ($$"hello\n"$$);
INSERT INTO test_strings VALUES ($$"hello"$$);
INSERT INTO test_strings VALUES ($$3$$);
INSERT INTO test_strings VALUES ($$3.$$);
INSERT INTO test_strings VALUES ($$.3$$);
INSERT INTO test_strings VALUES ($$0.3$$);
INSERT INTO test_strings VALUES ($$0.3e$$);
INSERT INTO test_strings VALUES ($$0.3e+$$);
INSERT INTO test_strings VALUES ($$0.3e+5$$);
INSERT INTO test_strings VALUES ($$0.3e-5$$);
INSERT INTO test_strings VALUES ($$0.3e5$$);
INSERT INTO test_strings VALUES ($$"hello"$$);
INSERT INTO test_strings VALUES ($$+3$$);
INSERT INTO test_strings VALUES ($$-3$$);
INSERT INTO test_strings VALUES ($$-3.$$);
INSERT INTO test_strings VALUES ($$-3.1$$);
INSERT INTO test_strings VALUES ($$.5$$);
INSERT INTO test_strings VALUES ($$5.$$);
INSERT INTO test_strings VALUES ($$5.e1$$);
INSERT INTO test_strings VALUES ($$0.5$$);
INSERT INTO test_strings VALUES ($$.3e1$$);
INSERT INTO test_strings VALUES ($$.3e+1$$);
INSERT INTO test_strings VALUES ($$.3e-1$$);
INSERT INTO test_strings VALUES ($$.3e-1 .5$$);
INSERT INTO test_strings VALUES ($$.3e-1.5$$);
INSERT INTO test_strings VALUES ($$.3e+1.5$$);
INSERT INTO test_strings VALUES ($$.3e+.$$);
INSERT INTO test_strings VALUES ($$.3e+.5$$);
INSERT INTO test_strings VALUES ($$.3e+1.5$$);
INSERT INTO test_strings VALUES ($$9.3e+1.5$$);
INSERT INTO test_strings VALUES ($$9.e+1.5$$);
INSERT INTO test_strings VALUES ($$9.e+$$);
INSERT INTO test_strings VALUES ($$9.e+1$$);
INSERT INTO test_strings VALUES ($$"\""$$);
INSERT INTO test_strings VALUES ($$"\"3.5"$$);
INSERT INTO test_strings VALUES ($$"\"."$$);
INSERT INTO test_strings VALUES ($$"\".".$$);
INSERT INTO test_strings VALUES ($$"\"....."$$);
INSERT INTO test_strings VALUES ($$"\"\"\"\"""$$);
INSERT INTO test_strings VALUES ($$["\"\"\"\"", .5]$$);
INSERT INTO test_strings VALUES ($$[.5]$$);
INSERT INTO test_strings VALUES ($$["\"\"\"\"", 0.5]$$);
INSERT INTO test_strings VALUES ($$["\"\"\"\"", .5]$$);
INSERT INTO test_strings VALUES ($$["\"\"\"\"",.5]$$);
INSERT INTO test_strings VALUES ($$["\"",.5]$$);
INSERT INTO test_strings VALUES ($$["\".5",.5]$$);
INSERT INTO test_strings VALUES ($$["\".5",".5\"".5]$$);
INSERT INTO test_strings VALUES ($$["\".5",".5\"", .5]$$);
INSERT INTO test_strings VALUES ($$["\".5",".5\"",.5]$$);
INSERT INTO test_strings VALUES ($$["\".5",".5\"",0.5]$$);
INSERT INTO test_strings VALUES ($${"key":/*comment*/"value"}$$);
INSERT INTO test_strings VALUES ($${"key":/*comment"value"}$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/*$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/**/$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/***/$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/**//$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/**///$$);
INSERT INTO test_strings VALUES ($${"key":"value"}/**///----$$);
INSERT INTO test_strings VALUES ($${"key":"value"}#$$);
INSERT INTO test_strings VALUES ($${"key":"value"}#{$$);
INSERT INTO test_strings VALUES ($${"key":"value"}#{}$$);
INSERT INTO test_strings VALUES ($${"key":"value"}#,$$);
INSERT INTO test_strings VALUES ($${"key":"value"/**/, "k2":"v2"}$$);
INSERT INTO test_strings VALUES ($$"\u0027"$$);
INSERT INTO test_strings VALUES ($$"hello\'"$$);
INSERT INTO test_strings VALUES ($$'hello\''$$);
INSERT INTO test_strings VALUES ($$'hello'$$);
INSERT INTO test_strings VALUES ($$'hell\'o'$$);
INSERT INTO test_strings VALUES ($$'\'hello'$$);
INSERT INTO test_strings VALUES ($$'\'hello\''$$);
INSERT INTO test_strings VALUES ($$\'hello\'$$);
INSERT INTO test_strings VALUES ($$'hello\'$$);
INSERT INTO test_strings VALUES ($$['hello\']$$);
INSERT INTO test_strings VALUES ($$['hello\'']$$);
INSERT INTO test_strings VALUES ($$['hello"']$$);
INSERT INTO test_strings VALUES ($$['hello\"']$$);
INSERT INTO test_strings VALUES ($$['hello"o']$$);
INSERT INTO test_strings VALUES ($$['"']$$);
INSERT INTO test_strings VALUES ($$'"'$$);
INSERT INTO test_strings VALUES ($$'"hello"'$$);
INSERT INTO test_strings VALUES ($$'"hello'$$);
INSERT INTO test_strings VALUES ($$'"hi"'$$);
INSERT INTO test_strings VALUES (E'\t [ 1 , 2 , 3 ]    ');
INSERT INTO test_strings VALUES ($$nil$$);
INSERT INTO test_strings VALUES ($$fals$$);
INSERT INTO test_strings VALUES ($$falsify$$);
INSERT INTO test_strings VALUES ($$falsetto$$);
INSERT INTO test_strings VALUES ($$truism$$);
INSERT INTO test_strings VALUES ($${"key"$$);
INSERT INTO test_strings VALUES ($${"key","key2":null}$$);
INSERT INTO test_strings VALUES ($$"\u0000"$$);

COMMIT;
